Repository UltimateCodeMonkeys/CodeMonkeys, pull requests merged in 2020-11, with the labels that each got.

#158 bugfix by changing firstordefault to foreach loop
  samples/ViewModels/NestedViewModel.cs
  src/MVVM/PropertyChanged/BindingBase/BindingBase.propertyChanged.cs
Labels: Bugfix, MVVM, Priority: High

#159 Merge maintenance/upgrade-xamarin-forms-version into develop
  samples/Xamarin.Forms/TabbedSample/TabbedSample/TabbedSample.csproj
  src/Dialogs/Dialogs.Xamarin.Forms/Dialogs.Xamarin.Forms.csproj
  src/Navigation/Xamarin.Forms/Navigation.Xamarin.Forms/Navigation.Xamarin.Forms.csproj
  src/tests/UnitTests/UnitTests.csproj
Labels: Public Release, Type: Maintenance

#167 Merge bugfix/dependency-resolver-not-registered into develop
  src/DependencyInjection/DependencyInjection/DependencyContainerFactory.cs
Labels: Bugfix, Priority: High, Public Release

#168 Merge bugfix/153-dialog-service-throws-argumentnullexception into develop
  src/Dialogs/Dialogs.Xamarin.Forms/DialogService.cs
  src/Dialogs/Dialogs/Extensions/DialogServiceExtensions.cs
  src/Dialogs/Dialogs/Models/AlertDialog.cs
  src/Dialogs/Dialogs/Models/ConfirmationDialog.cs
  src/Dialogs/Dialogs/Models/Dialog.cs
  src/Dialogs/Dialogs/Models/DialogButton.cs
  src/Dialogs/Dialogs/Models/ErrorDialog.cs
Labels: Breaking Changes, Bugfix, Priority: High, Public Release

#171 Merge bugfix/169-getvalue-with-generic-type-string-wrong-value into develop
  src/Dialogs/Dialogs/DialogOptions.cs
  src/Logging/Logging.File/FileLogOptions.cs
  src/Logging/Logging/LogOptions.cs
Labels: Bugfix, Public Release

#172 Merge bugfix/navigation-registration-condition-not-used into develop
  samples/Xamarin.Forms/TabbedSample/TabbedSample/App.xaml.cs
  samples/Xamarin.Forms/TabbedSample/TabbedSample/TabbedSample.csproj
Labels: Bugfix, Navigation, Navigation.Forms, Navigation.WPF, Public Release
